name: .NET Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore Wrap.Remastered.sln

    - name: Build Server
      run: dotnet build Wrap.Remastered.Server/Wrap.Remastered.Server.csproj --configuration Debug --no-restore

    - name: Build Console Client
      run: dotnet build Wrap.Remastered.Console/Wrap.Remastered.Console.csproj --configuration Debug --no-restore

    - name: Upload Server Artifact
      uses: actions/upload-artifact@v4
      with:
        name: server
        path: Wrap.Remastered.Server/bin/Debug/net8.0

    - name: Upload Console Client Artifact
      uses: actions/upload-artifact@v4
      with:
        name: console-client
        path: Wrap.Remastered.Console/bin/Debug/net8.0